version: '3.7'
services:
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: 'mysql/mysql-server:8.0'
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./dockercompose/mysql:/var/lib/mysql
    networks:
      - sa-network

  mysqlshadow:
    container_name: mysqlshadow
    command: --default-authentication-plugin=mysql_native_password
    image: 'mysql/mysql-server:8.0'
    restart: always
    environment:
      MYSQL_DATABASE: 'shadow'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '127.0.0.1:3307:3306'
    volumes:
      - ./dockercompose/mysqlshadow:/var/lib/mysql
    networks:
      - sa-network

networks:
  sa-network:
    name: sa-network
    driver: bridge
